#:copyright: Copyright (c) 2016 RadiaSoft LLC.  All Rights Reserved.
#:license: http://www.apache.org/licenses/LICENSE-2.0.html

FROM {{ script.base_container }}

WORKDIR /contester_prepare

USER 0

{% if script.packages is not none %}
RUN dnf -y {{ ' '.join(script.packages) }}
{% endif %}

{% if script.files is not none %}
COPY {{ ' '.join(script.files) }} /contester_prepare
{% endif %}

USER 1000

{% if script.prepare_script is not none %}
RUN /bin/bash -l -c '{{ ' && '.join(script.prepare_script) }}'
{% endif %}

LABEL org.radiasoft.contester.branch={{ git_branch }} \
      org.radiasoft.contester.commit={{ git_commit }} \
      org.radiasoft.contester.dirty={{ git_dirty }} \
      org.radiasoft.contester.name={{ git_name }}
